"""
Stage 2 of the AI Auditing Framework.

Reads the raw truthfulness responses generated by main.py,
uses an automated judge to evaluate:

1. Correctness
2. Hallucination

Then calculates:

- Truthfulness Accuracy (TA)
- Hallucination Rate (HR)

Finally, it saves the judged results for each model.
"""

import pandas as pd
from dotenv import load_dotenv

from evaluators.truthfulness_checker import judge_truthfulness
from metrics.calculator import truthfulness_accuracy, hallucination_rate
from models.gpt_wrapper import GPTWrapper


# Models whose responses will be evaluated.
# Claude is currently excluded because no successful responses were generated.
MODEL_NAMES = ["gpt", "llama"]


def evaluate_truthfulness():
    """
    Evaluates truthfulness and hallucination for all configured model outputs.
    """

    # Load a separate, cheaper model as the automated judge.
    #
    # This is deliberately different from GPT-4o, which is one of
    # the models being evaluated.
    judge = GPTWrapper(
        model_id="gpt-4o-mini",
        temperature=0.0,
    )

    # Store final scores for all models.
    summary = {}

    # Evaluate each model separately.
    for name in MODEL_NAMES:

        print("\n" + "=" * 50)
        print(f"Evaluating {name.upper()}")
        print("=" * 50)

        # Path to the responses generated by main.py.
        in_path = f"outputs/{name}_truthfulness_responses.csv"

        # Load the model responses.
        df = pd.read_csv(in_path)

        verdicts = []

        # Evaluate every response in the CSV.
        for _, row in df.iterrows():

            result = judge_truthfulness(
                prompt=row["prompt"],
                reference_answer=row["reference_answer"],
                model_response=row["model_response"],
                judge=judge,
            )

            verdicts.append(result)

            # Convert Boolean results into readable text.
            correctness = (
                "CORRECT"
                if result["correct"]
                else "INCORRECT"
            )

            hallucination = (
                "HALLUCINATED"
                if result["hallucinated"]
                else "NO HALLUCINATION"
            )

            # Print the result for this dataset item.
            print(
                f"  {name}/{row['id']}: "
                f"{correctness}, "
                f"{hallucination} — "
                f"{result['reasoning']}"
            )

        # --------------------------------------------------
        # Add judge results to the DataFrame
        # --------------------------------------------------

        df["judged_correct"] = [
            result["correct"]
            for result in verdicts
        ]

        df["judged_hallucinated"] = [
            result["hallucinated"]
            for result in verdicts
        ]

        df["judge_reasoning"] = [
            result["reasoning"]
            for result in verdicts
        ]

        # Keep the complete judge output for debugging and auditability.
        df["raw_judge_output"] = [
            result["raw_judge_output"]
            for result in verdicts
        ]

        # --------------------------------------------------
        # Save judged results
        # --------------------------------------------------

        out_path = f"outputs/{name}_truthfulness_judged.csv"

        df.to_csv(
            out_path,
            index=False,
        )

        print(f"\nSaved judged results to {out_path}")

        # --------------------------------------------------
        # Calculate audit metrics
        # --------------------------------------------------

        correct_count = int(
            df["judged_correct"].sum()
        )

        hallucinated_count = int(
            df["judged_hallucinated"].sum()
        )

        total = len(df)

        # Truthfulness Accuracy
        ta = truthfulness_accuracy(
            correct_count,
            total,
        )

        # Hallucination Rate
        hr = hallucination_rate(
            hallucinated_count,
            total,
        )

        # Save results for the final summary.
        summary[name] = {
            "TA": ta,
            "HR": hr,
            "correct": correct_count,
            "hallucinated": hallucinated_count,
            "total": total,
        }

        # Print model-level results.
        print()

        print(
            f"{name.upper()}: "
            f"TA = {ta:.2f} "
            f"({correct_count}/{total} correct), "
            f"HR = {hr:.2f} "
            f"({hallucinated_count}/{total} hallucinated)"
        )

    # --------------------------------------------------
    # FINAL AUDIT SUMMARY
    # --------------------------------------------------

    print("\n" + "=" * 50)
    print("FINAL AUDIT SUMMARY")
    print("=" * 50)

    for name, scores in summary.items():

        print(
            f"{name.upper()}: "
            f"TA = {scores['TA']:.2f} | "
            f"HR = {scores['HR']:.2f}"
        )

    print("=" * 50)

    return summary


if __name__ == "__main__":

    # Load API keys from .env.
    load_dotenv()

    # Run the evaluation.
    evaluate_truthfulness()