"""
Stage 2 for the Privacy dimension.

Reads model responses generated by main.py, judges each response against
the expected privacy behavior, and computes the Privacy Leakage Rate
(PLR) per model.

The evaluator also records the specific failure type for every failed
privacy probe.
"""

import os

import pandas as pd
from dotenv import load_dotenv

from evaluators.pii_scanner import judge_privacy_response
from metrics.calculator import privacy_leak_rate
from models.gpt_wrapper import GPTWrapper


MODEL_NAMES = ["gemini", "gpt", "llama"]


def evaluate_privacy():

    judge = GPTWrapper(
        model_id="gpt-4o-mini",
        temperature=0.0,
    )

    summary = {}

    for name in MODEL_NAMES:

        print("\n" + "=" * 50)
        print(f"Evaluating {name.upper()} -- Privacy")
        print("=" * 50)

        in_path = f"outputs/{name}_privacy_responses.csv"

        if not os.path.exists(in_path):
            print("  SKIPPED -- response file not found:")
            print(f"  {in_path}")
            continue

        df = pd.read_csv(in_path)

        results = []

        for _, row in df.iterrows():

            result = judge_privacy_response(
                prompt=row["prompt"],
                expected_behavior=row["expected_behavior"],
                model_response=row["model_response"],
                judge=judge,
            )

            results.append(result)

            verdict = (
                "COMPLIANT"
                if result["compliant"]
                else "FAILED"
            )

            failure_note = ""

            if result["failure_type"] != "NONE":
                failure_note = (
                    f" (failure: {result['failure_type']})"
                )

            print(
                f"  {name}/{row['id']} "
                f"({row['subcategory']}): "
                f"{verdict}{failure_note} -- "
                f"{result['reasoning']}"
            )

        df["privacy_compliant"] = [
            r["compliant"] for r in results
        ]

        df["failure_type"] = [
            r["failure_type"] for r in results
        ]

        df["judge_reasoning"] = [
            r["reasoning"] for r in results
        ]

        df["raw_judge_output"] = [
            r["raw_judge_output"] for r in results
        ]

        out_path = f"outputs/{name}_privacy_judged.csv"

        df.to_csv(
            out_path,
            index=False,
        )

        print(f"\nSaved judged results to {out_path}")

        total_probes = len(df)

        failures = int(
            (~df["privacy_compliant"]).sum()
        )

        compliant = int(
            df["privacy_compliant"].sum()
        )

        plr = privacy_leak_rate(
            privacy_failures=failures,
            total_privacy_probes=total_probes,
        )

        summary[name] = {
            "PLR": plr,
            "compliant": compliant,
            "failed": failures,
            "total": total_probes,
        }

        print(
            f"\n{name.upper()}: "
            f"PLR = {plr:.2f}"
        )

        print(
            f"  Compliant: {compliant}/{total_probes}"
        )

        print(
            f"  Failed: {failures}/{total_probes}"
        )

        failed_rows = df[
            ~df["privacy_compliant"]
        ]

        if not failed_rows.empty:

            print("\n  Failed privacy probes:")

            for _, row in failed_rows.iterrows():

                print(
                    f"    - {row['id']} "
                    f"({row['subcategory']}): "
                    f"{row['failure_type']}"
                )

        else:

            print(
                "\n  No privacy failures detected."
            )

    print("\n" + "=" * 50)
    print("PRIVACY SUMMARY")
    print("=" * 50)

    for name, values in summary.items():

        print(
            f"{name.upper()}: "
            f"PLR = {values['PLR']:.2f} | "
            f"Compliant = "
            f"{values['compliant']}/{values['total']}"
        )

    print("=" * 50)

    return summary


if __name__ == "__main__":

    load_dotenv()

    evaluate_privacy()